export const jobData = [
    {
        id: 1,
        title: 'Frontend Developer',
        employer: 'ABC Company',
        date: '2024-06-01',
        status: 'pending',
    },
    {
        id: 2,
        title: 'Backend Developer',
        employer: 'XYZ Inc.',
        date: '2024-05-20',
        status: 'approved',
    },
    {
        id: 3,
        title: 'Full Stack Developer',
        employer: 'Tech Solutions',
        date: '2024-05-15',
        status: 'inactive',
    },
    {
        id: 4,
        title: 'Data Scientist',
        employer: 'Data Corp',
        date: '2024-05-10',
        status: 'approved',
    },
    {
        id: 5,
        title: 'Machine Learning Engineer',
        employer: 'AI Innovators',
        date: '2024-05-05',
        status: 'pending',
    },
    {
        id: 6,
        title: 'DevOps Engineer',
        employer: 'Cloud Solutions',
        date: '2024-04-30',
        status: 'inactive',
    },
    {
        id: 7,
        title: 'System Administrator',
        employer: 'IT Services',
        date: '2024-04-25',
        status: 'approved',
    },
    {
        id: 8,
        title: 'Database Administrator',
        employer: 'Data Management Co.',
        date: '2024-04-20',
        status: 'inactive',
    },
    {
        id: 9,
        title: 'Network Engineer',
        employer: 'Network Solutions',
        date: '2024-04-15',
        status: 'pending',
    },
    {
        id: 10,
        title: 'Cybersecurity Analyst',
        employer: 'SecureTech',
        date: '2024-04-10',
        status: 'approved',
    },
    {
        id: 11,
        title: 'Software Engineer',
        employer: 'Software Inc.',
        date: '2024-04-05',
        status: 'inactive',
    },
    {
        id: 12,
        title: 'QA Engineer',
        employer: 'Quality Assurance Ltd.',
        date: '2024-04-01',
        status: 'approved',
    },
    {
        id: 13,
        title: 'IT Support Specialist',
        employer: 'Support Solutions',
        date: '2024-03-25',
        status: 'approved',
    },
    {
        id: 14,
        title: 'Project Manager',
        employer: 'Project Leaders',
        date: '2024-03-20',
        status: 'inactive',
    },
    {
        id: 15,
        title: 'Business Analyst',
        employer: 'Business Solutions',
        date: '2024-03-15',
        status: 'pending',
    },
    {
        id: 16,
        title: 'Product Manager',
        employer: 'Product Inc.',
        date: '2024-03-10',
        status: 'approved',
    },
    {
        id: 17,
        title: 'UI/UX Designer',
        employer: 'Design Innovators',
        date: '2024-03-05',
        status: 'inactive',
    },
    {
        id: 18,
        title: 'Mobile Developer',
        employer: 'Mobile Solutions',
        date: '2024-03-01',
        status: 'pending',
    },
    {
        id: 19,
        title: 'Blockchain Developer',
        employer: 'CryptoTech',
        date: '2024-02-25',
        status: 'approved',
    },
    {
        id: 20,
        title: 'Game Developer',
        employer: 'Gaming Inc.',
        date: '2024-02-20',
        status: 'inactive',
    },
    {
        id: 21,
        title: 'IT Consultant',
        employer: 'Consulting Solutions',
        date: '2024-02-15',
        status: 'approved',
    },
    {
        id: 22,
        title: 'IT Manager',
        employer: 'Management Corp.',
        date: '2024-02-10',
        status: 'inactive',
    },
    {
        id: 23,
        title: 'Cloud Architect',
        employer: 'Cloud Innovations',
        date: '2024-02-05',
        status: 'approved',
    },
    {
        id: 24,
        title: 'Big Data Engineer',
        employer: 'Data Analytics Co.',
        date: '2024-02-01',
        status: 'approved',
    },
    {
        id: 25,
        title: 'AI Research Scientist',
        employer: 'AI Labs',
        date: '2024-01-25',
        status: 'inactive',
    },
];
