// <auto-generated />
using EmployerService.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EmployerService.Migrations.Shard2MasterDb
{
    [DbContext(typeof(Shard2MasterDbContext))]
    [Migration("20240623080646_Init")]
    partial class Init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("EmployerService.Domain.Entities.Company", b =>
                {
                    b.Property<string>("CompanyId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyOverview")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanySize")
                        .HasColumnType("longtext");

                    b.Property<string>("CompanyType")
                        .HasColumnType("longtext");

                    b.Property<string>("Country")
                        .HasColumnType("longtext");

                    b.Property<string>("EmployerId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Image")
                        .HasColumnType("longtext");

                    b.Property<string>("KeySkills")
                        .HasColumnType("longtext");

                    b.Property<string>("Location")
                        .HasColumnType("longtext");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("longtext");

                    b.Property<string>("OvertimePolicy")
                        .HasColumnType("longtext");

                    b.Property<string>("WhyLoveWorkingHere")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkType")
                        .HasColumnType("longtext");

                    b.Property<string>("WorkingDays")
                        .HasColumnType("longtext");

                    b.HasKey("CompanyId");

                    b.ToTable("Companies");
                });
#pragma warning restore 612, 618
        }
    }
}
