name: CI

on:
  push:
    branches:
      - job/job-search-service

jobs:
  test-job-service:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 19
        uses: actions/setup-java@v1
        with:
          java-version: '19'

      - name: Run tests for job-service
        run: |
          cd Microservices/job-service
          mvn test
