name: Build and deploy Notification Service to Cloud Run

on:
  push:
    branches:
    - feature/notification-service

env:
  GCP_PROJECT: ${{ secrets.GCP_PROJECT }}
  CONFIGURATION: Release
  DOTNET_CORE_VERSION: 6.0.x
  WORKING_DIRECTORY: ./Microservices/notification-service/NotificationService

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

      - name: Build the project
        run: dotnet build ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }}

      - name: Publish the project
        run: dotnet publish ${{ env.WORKING_DIRECTORY }} --configuration ${{ env.CONFIGURATION }} --output ${{ env.WORKING_DIRECTORY }}/published

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Build and push Docker image
        run: |
          cd ${{ env.WORKING_DIRECTORY }}
          IMAGE_NAME=gcr.io/${{ env.GCP_PROJECT }}/notification-service
          gcloud builds submit --tag $IMAGE_NAME .

      - name: Deploy to Cloud Run
        run: |
          IMAGE_NAME=gcr.io/${{ env.GCP_PROJECT }}/notification-service
          gcloud run deploy notification-service --image $IMAGE_NAME --region us-central1 --platform managed --allow-unauthenticated
